admin:
  id: 
  url: 
cookie:
  expiry_days: 30
  key: zonynnyakxjtein
  name: ppjrsyesswuqjtj
credentials:
  usernames: {}
preauthorized:
  emails:
telegram:
  token: 6092531525:AAFctwgkmVgGTP1XsJooatyplmxg9KB6LRs
engines:
  large: 1
  short: 1